# List of locales supported by Microsoft translator for LocalizationEditor : MIT License
# @author Vladimir Petrenko
# @see https://translator.microsoft.com/
extends Object
class_name LocalizationAutoTranslateMicrosoft

static func locales() -> Array: #[LocalizationLocaleSingle]:
	return [
		LocalizationLocaleSingle.new("BG", "Bulgarian"),
		LocalizationLocaleSingle.new("af", "Afrikaans"),
		LocalizationLocaleSingle.new("sq", "Albanisch"),
		LocalizationLocaleSingle.new("am", "Amharisch"),
		LocalizationLocaleSingle.new("ar", "Arabisch"),
		LocalizationLocaleSingle.new("hy", "Armenisch"),
		LocalizationLocaleSingle.new("as", "Assamesisch"),
		LocalizationLocaleSingle.new("az", "Aserbaidschanisch (Lateinisch)"),
		LocalizationLocaleSingle.new("bn", "Bengalisch"),
		LocalizationLocaleSingle.new("ba", "Baschkirisch"),
		LocalizationLocaleSingle.new("eu", "Baskisch"),
		LocalizationLocaleSingle.new("bs", "Bosnisch (Lateinisch)"),
		LocalizationLocaleSingle.new("bg", "Bulgarisch"),
		LocalizationLocaleSingle.new("yue", "Chinesisch (traditionell)"),
		LocalizationLocaleSingle.new("ca", "Katalanisch"),
		LocalizationLocaleSingle.new("lzh", "Chinesisch (literarisch)"),
		LocalizationLocaleSingle.new("zh-Hans", "Chinesisch (vereinfacht)"),
		LocalizationLocaleSingle.new("zh-Hant", "Chinesisch (traditionell)"),
		LocalizationLocaleSingle.new("hr", "Kroatisch"),
		LocalizationLocaleSingle.new("cs", "Tschechisch"),
		LocalizationLocaleSingle.new("da", "Dänisch"),
		LocalizationLocaleSingle.new("prs", "Dari"),
		LocalizationLocaleSingle.new("dv", "Divehi"),
		LocalizationLocaleSingle.new("nl", "Niederländisch"),
		LocalizationLocaleSingle.new("en", "Englisch"),
		LocalizationLocaleSingle.new("et", "Estnisch"),
		LocalizationLocaleSingle.new("fo", "Färöisch"),
		LocalizationLocaleSingle.new("fj", "Fidschi"),
		LocalizationLocaleSingle.new("fil", "Filipino"),
		LocalizationLocaleSingle.new("fi", "Finnisch"),
		LocalizationLocaleSingle.new("fr", "Französisch"),
		LocalizationLocaleSingle.new("fr-ca", "Französisch (Kanada)"),
		LocalizationLocaleSingle.new("gl", "Galizisch"),
		LocalizationLocaleSingle.new("ka", "Georgisch"),
		LocalizationLocaleSingle.new("de", "Deutsch"),
		LocalizationLocaleSingle.new("el", "Griechisch"),
		LocalizationLocaleSingle.new("gu", "Gujarati"),
		LocalizationLocaleSingle.new("ht", "Haitianisches Kreolisch"),
		LocalizationLocaleSingle.new("he", "Hebräisch"),
		LocalizationLocaleSingle.new("hi", "Hindi"),
		LocalizationLocaleSingle.new("mww", "Hmong Daw (Lateinisch)"),
		LocalizationLocaleSingle.new("hu", "Ungarisch"),
		LocalizationLocaleSingle.new("is", "Isländisch"),
		LocalizationLocaleSingle.new("id", "Indonesisch"),
		LocalizationLocaleSingle.new("ikt", "Inuinnaqtun"),
		LocalizationLocaleSingle.new("iu", "Inuktitut"),
		LocalizationLocaleSingle.new("iu-Latn", "Inuktitut (Lateinisch)"),
		LocalizationLocaleSingle.new("ga", "Irisch"),
		LocalizationLocaleSingle.new("it", "Italienisch"),
		LocalizationLocaleSingle.new("ja", "Japanisch"),
		LocalizationLocaleSingle.new("kn", "Kannada"),
		LocalizationLocaleSingle.new("kk", "Kasachisch"),
		LocalizationLocaleSingle.new("km", "Khmer"),
		LocalizationLocaleSingle.new("tlh-Latn", "Klingonisch"),
		LocalizationLocaleSingle.new("tlh-Piqd", "Klingonisch (plqaD)"),
		LocalizationLocaleSingle.new("ko", "Koreanisch"),
		LocalizationLocaleSingle.new("ku", "Kurdisch (zentral)"),
		LocalizationLocaleSingle.new("kmr", "Kurdisch (nördlich)"),
		LocalizationLocaleSingle.new("ky", "Kirgisisch (Kyrillisch)"),
		LocalizationLocaleSingle.new("lo", "Laotisch"),
		LocalizationLocaleSingle.new("lv", "Lettisch"),
		LocalizationLocaleSingle.new("lt", "Litauisch"),
		LocalizationLocaleSingle.new("mk", "Mazedonisch"),
		LocalizationLocaleSingle.new("mg", "Madagassisch"),
		LocalizationLocaleSingle.new("ms", "Malaiisch (Lateinisch)"),
		LocalizationLocaleSingle.new("ml", "Malayalam"),
		LocalizationLocaleSingle.new("mt", "Maltesisch"),
		LocalizationLocaleSingle.new("mi", "Maori"),
		LocalizationLocaleSingle.new("mr", "Marathi"),
		LocalizationLocaleSingle.new("mn-Cyrl", "Mongolisch (Kyrillisch)"),
		LocalizationLocaleSingle.new("mn-Mong", "Mongolisch (traditionell)"),
		LocalizationLocaleSingle.new("my", "Myanmar"),
		LocalizationLocaleSingle.new("ne", "Nepalesisch"),
		LocalizationLocaleSingle.new("nb", "Norwegisch"),
		LocalizationLocaleSingle.new("or", "Odia"),
		LocalizationLocaleSingle.new("ps", "Paschtu"),
		LocalizationLocaleSingle.new("fa", "Persisch"),
		LocalizationLocaleSingle.new("pl", "Polnisch"),
		LocalizationLocaleSingle.new("pt", "Portugiesisch (Brasilien)"),
		LocalizationLocaleSingle.new("pt-pt", "Portugiesisch (Portugal)"),
		LocalizationLocaleSingle.new("pa", "Pandschabi"),
		LocalizationLocaleSingle.new("otq", "Queretaro-Otomi"),
		LocalizationLocaleSingle.new("ro", "Rumänisch"),
		LocalizationLocaleSingle.new("ru", "Russisch"),
		LocalizationLocaleSingle.new("sm", "Samoanisch (Lateinisch)"),
		LocalizationLocaleSingle.new("sr-Cyrl", "Serbisch (Kyrillisch)"),
		LocalizationLocaleSingle.new("sr-Latn", "Serbisch (Lateinisch)"),
		LocalizationLocaleSingle.new("sk", "Slowakisch"),
		LocalizationLocaleSingle.new("sl", "Slowenisch"),
		LocalizationLocaleSingle.new("so", "Somali (Arabisch)"),
		LocalizationLocaleSingle.new("es", "Spanisch"),
		LocalizationLocaleSingle.new("sw", "Suaheli (Lateinisch)"),
		LocalizationLocaleSingle.new("sv", "Schwedisch"),
		LocalizationLocaleSingle.new("ty", "Tahitisch"),
		LocalizationLocaleSingle.new("ta", "Tamilisch"),
		LocalizationLocaleSingle.new("tt", "Tatarisch (Lateinisch)"),
		LocalizationLocaleSingle.new("te", "Telugu"),
		LocalizationLocaleSingle.new("th", "Thailändisch"),
		LocalizationLocaleSingle.new("bo", "Tibetisch"),
		LocalizationLocaleSingle.new("ti", "Tigrinya"),
		LocalizationLocaleSingle.new("to", "Tongaisch"),
		LocalizationLocaleSingle.new("tr", "Türkisch"),
		LocalizationLocaleSingle.new("tk", "Turkmenisch (Lateinisch)"),
		LocalizationLocaleSingle.new("uk", "Ukrainisch"),
		LocalizationLocaleSingle.new("hsb", "Obersorbisch"),
		LocalizationLocaleSingle.new("ur", "Urdu"),
		LocalizationLocaleSingle.new("ug", "Uigurisch (Arabisch)"),
		LocalizationLocaleSingle.new("uz", "Usbekisch (lateinisch)"),
		LocalizationLocaleSingle.new("vi", "Vietnamesisch"),
		LocalizationLocaleSingle.new("cy", "Walisisch"),
		LocalizationLocaleSingle.new("yua", "Yukatekisches Maya"),
		LocalizationLocaleSingle.new("zu", "Zulu")
	]

static func label_by_code(code: String) -> String:
	for locale in locales():
		if locale.code == code:
			return locale.code + " " + locale.name
	return ""
